### ISSUE TITLE
Разобраться с FFMpeg NOOOO

### ISSUE THREAD

**Issue by anatoliyfedorenko** [go-courses/youtubebot#13]

**Comment by medalon** [comment]
Установим в Убунту: sudo aptitude install ffmpeg

**Comment by anatoliyfedorenko** [comment]
Написали функцию Convert 

func Convert(title, url string) error {
	fileName := fmt.Sprintf("files/%s.mp3", title)
	ffmpegArgs := []string{
		"-i", url,
		"-headers", "User-Agent: Go-http-client/1.1",
		"-codec:a", "libmp3lame", "-qscale:a", "2", fileName,
	}
	cmd := exec.Command("ffmpeg", ffmpegArgs...)
	err := cmd.Run()
	if err != nil {
		return err
	}
	return nil
}

Фунцкция принимает 2 параметра. 1) Название файла, чтобы потом как-то назвать файл, который она сохраняет. 2) url файла в виде строки. 

Задаётся параметр имени. 
Потом мы создаём лист параметров для утилиты ffmpeg. 
Через командную строку Lunix запускаем ffmpeg с заданными параметрами. и запускаем этот код.
